stop errors like: "ActionError: Invalid mouse spec: 'scrollup:8' (in 'scrollup:8')"
stop errors complaining of invalid scroll(up,down), may be because i don't have eye_tracker, will investigate later
...
Unable to open: /dotfiles/words.txt
Error loading _repeat from C:\Users\Me\Documents\Natlink\_repeat.py
Traceback (most recent call last):
  File "C:\NatLink\NatLink\MacroSystem\core\natlinkmain.py", line 317, in loadFile
    imp.load_module(modName,fndFile,fndName,fndDesc)
  File "C:\Users\Me\Documents\Natlink\_repeat.py", line 346, in <module>
    "scrup": Function(lambda: eye_tracker.move_to_position((0, 50))) + Mouse("scrollup:8"),
  File "C:\Python27\lib\site-packages\dragonfly-0.6.6b1-py2.7.egg\dragonfly\actions\action_mouse.py", line 277, in __init__
    DynStrActionBase.__init__(self, spec=spec, static=static)
  File "C:\Python27\lib\site-packages\dragonfly-0.6.6b1-py2.7.egg\dragonfly\actions\action_base.py", line 106, in __init__
    self.initialize(spec, static)
  File "C:\Python27\lib\site-packages\dragonfly-0.6.6b1-py2.7.egg\dragonfly\actions\action_base.py", line 116, in initialize
    self._events = self._parse_spec(spec)
  File "C:\Python27\lib\site-packages\dragonfly-0.6.6b1-py2.7.egg\dragonfly\actions\action_mouse.py", line 294, in _parse_spec
    % (part, spec))
ActionError: Invalid mouse spec: 'scrollup:8' (in 'scrollup:8')
Loading _winctrl
...